admin/protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{

	public function actions()
	{
		return array(
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
		);
	}

	// public function actionDummy()
	// {
	// 	// Dummy::createDummyProduct();
	// 	// echo '<META http-equiv="refresh" content="0;URL=http://localhost/dv-computers/home/dummy">';
		
	// 	$data = Data::model()->findAll('1 LIMIT '.$_GET['page'].', 30');
	// 	foreach ($data as $key => $value) {
	// 		// 106-large_default.jpg
	// 		$image_name = '';
	// 		if ($value->image != 'http://ufoelektronika.com/img/p/0.jpg') {
	// 			$url = $value->image;
	// 			$url = substr($url, 0, -4).'-large_default.jpg';
	// 			$image_name = Slug::create($value->id.'-'.$value->name).'.jpg';
	// 			$img = Yii::getPathOfAlias('webroot').'/images/product/'.$image_name;
	// 			@file_put_contents($img, file_get_contents($url));
	// 		}

	// 		$model = new PrdProduct;
	// 		$model->kode = $value->reference;
	// 		$model->image = $image_name;
	// 		$model->harga = $value->base_price;
	// 		$model->harga_coret = $value->base_price + ($value->base_price*20/100);
	// 		$model->stock = $value->qty;
	// 		$model->status = $value->status;
	// 		$model->save(false);

	// 		$modelDesc = new PrdProductDescription;
	// 		$modelDesc->product_id = $model->id;
	// 		$modelDesc->language_id = 2;
	// 		$modelDesc->name = $value->name;
	// 		$modelDesc->save(false);
	// 	}
	// 	echo '<a href="'.CHtml::normalizeUrl(array('dummy', 'page'=>$_GET['page']+30)).'">next</a>';

	// }

	public function actionMail()
	{
		$config = array(
			'to'=>array('deoryzpandu@gmail.com'),
			'subject'=>'['.Yii::app()->name.'] Contact from ',
			'message'=>'pesan yang saya kirim',
		);
		// kirim email
		Common::mail($config);
	}

	public function actionInput()
	{
		$data = Table61::model()->findAll();
		foreach ($data as $key => $value) {
			$model = new PrdProduct;
			$model->kode = $value->col_1;
			if ($value->col_7 != '') {
				copy(YiiBase::getPathOfAlias('webroot').'/images/precise/'.$value->col_7.'/COVER.jpg', YiiBase::getPathOfAlias('webroot').'/images/product/'.Slug::create($value->col_1).'-'.Slug::create($value->col_2).'-cover.jpg');
				$model->image = Slug::create($value->col_1).'-'.Slug::create($value->col_2).'-cover.jpg';
			}else{
				$model->image = '';
			}
			$model->harga = $value->col_6;
			$model->harga_coret = 0;
			$model->save(false);
			$dataDesc = new PrdProductDescription;
			$dataDesc->product_id = $model->id;
			$dataDesc->language_id = 2;
			$dataDesc->name = $value->col_2;
			$dataDesc->subtitle = $value->col_3;
			$dataDesc->desc = '<p>'.$value->col_4.'</p>';
			$dataDesc->save(false);
			$dataAttr = explode(',', $value->col_5);
			foreach ($dataAttr as $v) {
				$modelAttr = new PrdProductAttributes;
				$modelAttr->product_id = $model->id;
				$modelAttr->attribute = trim($v);
				$modelAttr->stock = 10;
				$modelAttr->price = $value->col_6;
				$modelAttr->save(false);
				$modelAttr->id_str = $modelAttr->id;
				$modelAttr->save(false);

			}
			if ($value->col_7 != '') {
				for ($i=1; $i < 7; $i++) { 
					$modelImage = new PrdProductImage;
					$modelImage->product_id = $model->id;
					copy(YiiBase::getPathOfAlias('webroot').'/images/precise/'.$value->col_7.'/'.$i.'.jpg', YiiBase::getPathOfAlias('webroot').'/images/product/'.Slug::create($value->col_1).'-'.Slug::create($value->col_2).'-photo'.$i.'.jpg');
					$modelImage->image = Slug::create($value->col_1).'-'.Slug::create($value->col_2).'-photo'.$i.'.jpg';
					$modelImage->save(false);
				}
			}



		}
	}

	public function actionIndex()
	{
		$this->redirect(array('/admin/'));
		// $criteria=new CDbCriteria;

		// $criteria->with = array('description', 'category', 'categories');

		// $criteria->order = 'date DESC';

		// $criteria->addCondition('status = "1"');
		// $criteria->addCondition('description.language_id = :language_id');
		// // $criteria->addCondition('categoryView.language_id = :language_id');
		// // $criteria->addCondition('categoryTitle.language_id = :language_id');
		// $criteria->params[':language_id'] = $this->languageID;

		// $criteria->addCondition('categories.category_id = :category');
		// $criteria->params['category'] = 1;

		// $pageSize = 12;

		// $product = new CActiveDataProvider('PrdProduct', array(
		// 	'criteria'=>$criteria,
		//     'pagination'=>array(
		//         'pageSize'=>$pageSize,
		//     ),
		// ));

		// $model = new ContactForm;
		// $model->scenario = 'insert';

		// $this->layout='//layouts/column1';
		// $this->render('index', array(
		// 	'product'=>$product,
		// 	'model'=>$model,
		// ));
	}

	public function actionCategory()
	{
		$this->layout='//layouts/column2';

		$this->render('category', array(
		));
	}

	public function actionProductDetail()
	{
		$this->layout='//layouts/column2';
		$this->pageTitle = 'Product Detail - '. $this->pageTitle;
		
		$this->render('product_detail', array(	
		));
	}

	public function actionPCart()
	{
		$this->layout='//layouts/column3';

		$this->render('carts', array(
		));
	}

	public function actionPCart2()
	{
		$this->layout='//layouts/column3';

		$this->render('carts2', array(
		));
	}

	public function actionPsuccesscart()
	{
		$this->layout='//layouts/column3';

		$this->render('success_cart', array(
		));
	}

	public function actionCaraBelanja()
	{
		$this->layout='//layouts/column2';

		$this->render('cara_belanja', array(
		));
	}

	public function actionInfoPengiriman()
	{
		$this->layout='//layouts/column3';

		$this->render('info_pengiriman', array(
		));
	}

	public function actionSyarat()
	{
		$this->layout='//layouts/column2';

		$this->render('syarat_ketentuan', array(
		));
	}

	public function actionFaq()
	{
		$this->layout='//layouts/column2';

		$criteria=new CDbCriteria;
		$criteria->with = array('description');
		$criteria->order = 't.id ASC';

		$criteria->addCondition('status = "1"');
		$criteria->addCondition('description.language_id = :language_id');
		$criteria->params[':language_id'] = $this->languageID;

		$pageSize = 100000;

		$dataFaq = new CActiveDataProvider('Faq', array(
			'criteria'=>$criteria,
		    'pagination'=>array(
		        'pageSize'=>$pageSize,
		    ),
		));

		$this->render('faq', array(
			'dataFaq'=>$dataFaq,
		));
	}

	public function actionPmyaccount()
	{
		$this->layout='//layouts/column3';

		$this->render('mydashboard', array(
		));
	}

	public function actionPcontact()
	{
		$model = new ContactForm;
		$model->scenario = 'insert';
		
		if(isset($_POST['ContactForm']))
		{
			if (!isset($_POST['g-recaptcha-response'])) {
				$this->redirect(array('home/career'));
	        }
	        

				$model->attributes=$_POST['ContactForm'];
				if($model->validate())
				{
			        $secret_key = "6Lc5ExQUAAAAAHgV4U_6krEDyf-ykhlx08mEgJek";
			        $response=file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=".$secret_key."&response=".$_POST['g-recaptcha-response']."&remoteip=".$_SERVER['REMOTE_ADDR']);
			        $response = json_decode($response);
			        if($response->success==false)
			        {
			          $model->addError('verifyCode','Pastikan anda sudah menyelesaikan captcha');
			        }else{
						// config email
						$messaged = $this->renderPartial('//mail/contact2',array(
							'model'=>$model,
						),TRUE);
						$config = array(
							'to'=>array($model->email, $this->setting['email'], $this->setting['contact_email']),
							'subject'=>'[UFO Elektronika] Contact from '.$model->email,
							'message'=>$messaged,
						);
						if ($this->setting['contact_cc']) {
							$config['cc'] = array($this->setting['contact_cc']);
						}
						if ($this->setting['contact_bcc']) {
							$config['bcc'] = array($this->setting['contact_bcc']);
						}
						// kirim email
						Common::mail($config);

						Yii::app()->user->setFlash('success','Trimakasih telah mengirimkan pesan kepada kami, kami akan segera membalas pesan anda');
						$this->refresh();
					}
				}


		}

		$this->layout='//layouts/column2';
		$this->pageTitle = 'Contact Us - '.$this->pageTitle;
		$this->render('pcontact', array(
			'model'	=>$model,
		));
	}

	public function actionPsaler()
	{
		
		$model = new ContactForm;
		$model->scenario = 'insert';
		
		if(isset($_POST['ContactForm']))
		{
			if (!isset($_POST['g-recaptcha-response'])) {
				$this->redirect(array('home/career'));
	        }
	        

				$model->attributes=$_POST['ContactForm'];
				if($model->validate())
				{
			        $secret_key = "6Lfhyf8SAAAAABJ2p1sV8mV790VW7LAVOsy2qile";
			        $response=file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=".$secret_key."&response=".$_POST['g-recaptcha-response']."&remoteip=".$_SERVER['REMOTE_ADDR']);
			        $response = json_decode($response);
			        // print_r($response);
			        // exit;
			        if($response->success==false)
			        {
			          $model->addError('verifyCode','Pastikan anda sudah menyelesaikan captcha');
			        }else{
						// config email
						$messaged = $this->renderPartial('//mail/saler',array(
							'model'=>$model,
						),TRUE);
						$config = array(
							'to'=>array($model->email, $this->setting['email'], $this->setting['contact_email']),
							'subject'=>'Hi, Ada pendaftaran wholesaler '.$model->email,
							'message'=>$messaged,
						);
						if ($this->setting['contact_cc']) {
							$config['cc'] = array($this->setting['contact_cc']);
						}
						if ($this->setting['contact_bcc']) {
							$config['bcc'] = array($this->setting['contact_bcc']);
						}
						// kirim email
						Common::mail($config);

						Yii::app()->user->setFlash('success','Trimakasih telah mengirimkan pesan kepada kami, kami akan segera membalas pesan anda');
						$this->refresh();
					}

				}

		}
		$this->layout='//layouts/column1';
		$this->render('psaler', array(
			'model'	=>$model,
		));
	}

	public function actionSugest()
	{

		if ($_POST['q'] != '') {

admin/protected/views/home/cara_beli.php
<section class="default_sc top_inside_pg_default">
  <div class="out_table">
    <div class="in_table">
      <div class="prelatife container">
        <h1 class="sub_titlepage"><?php echo $this->setting['cara_title'] ?></h1>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</section>
<section class="default_sc insides_middleDefaultpages back-white">
  <div class="prelatife container">
    <div class="clear height-50"></div><div class="height-5"></div>
    <div class="content-text text-center">
      <div class="mw820 tengah">
        <?php echo $this->setting['cara_content'] ?>
        <p class="fz17"><b>Cara melakukan pembelian / inkuiri produk secara partai</b></p>
      </div>
        <div class="clear height-40"></div>
        
        <div class="list_howto_buys_c">
          <div class="row default">
            
            <div class="col-md-3 col-sm-6">
              <div class="items">
                <div class="pict padding-bottom-25"><img src="<?php echo $this->assetBaseurl; ?>cbuy_icon_1.png" alt="" class="img-responsive center-block"></div>
                <div class="clear"></div>
                <div class="desc">
                  <p>Pilih kategori produk yang diinginkan dan klik produk yang anda inginkan.</p>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-6">
              <div class="items">
                <div class="pict padding-bottom-25"><img src="<?php echo $this->assetBaseurl; ?>cbuy_icon_2.png" alt="" class="img-responsive center-block"></div>
                <div class="clear"></div>
                <div class="desc">
                  <p>Setelah melihat detil produk, anda dapat memasukkan jumlah yang anda inginkan dan menekan tombol masuk ke daftar inkuiri.</p>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-6">
              <div class="items">
                <div class="pict padding-bottom-25"><img src="<?php echo $this->assetBaseurl; ?>cbuy_icon_3.png" alt="" class="img-responsive center-block"></div>
                <div class="clear"></div>
                <div class="desc">
                  <p>Inkuiri produk akan sementara masuk ke dalam daftar inkuiri yang dapat diakses pada bagian atas.</p>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-6">
              <div class="items">
                <div class="pict padding-bottom-25"><img src="<?php echo $this->assetBaseurl; ?>cbuy_icon_4.png" alt="" class="img-responsive center-block"></div>
                <div class="clear"></div>
                <div class="desc">
                  <p>Anda dapat menambah inkuiri lain dan setelahnya, anda dapat mengirim inkuiri dengan klik tombol enquire di atas.</p>
                </div>
              </div>
            </div>

          </div>
        </div>
        <!-- end list icon buy -->
        <div class="clear height-30"></div>
      <div class="clear"></div>
    </div>

    <div class="clear"></div>
  </div>
</section>

admin/protected/views/home/career.php
<div class="blocks_subpage_banner promotion mih393 inside_top_illustration" style="background: none; background-image: none;">
    <div class="picts_full">
      <img src="<?php echo Yii::app()->baseUrl.'/images/static/'.$this->setting['career_hero_image']; ?>" alt="<?php echo $this->setting['career_hero_title'] ?>" class="img-responsive center-block">  
    </div>
    
    <?php if ($this->setting['career_hero_title']): ?>
    <div class="outers_block_text">
      <div class="prelatife blocks_text">
        <h3 class="sub_title_p"><?php echo $this->setting['career_hero_title'] ?></h3>
      </div>
    </div>
    <?php endif; ?>
</div>
<script type="text/javascript">
  $(window).load(function(){
    if ( $(window).width() > 768 ) {
      var get_heightBanner = $('.blocks_subpage_banner.inside_top_illustration .picts_full').height();
      $('.blocks_subpage_banner.inside_top_illustration .outers_block_text').css('height', get_heightBanner+'px');
    }
  });
</script>

<div class="clear"></div>
<div class="subpage static_about">
  <section class="default_sc back-black conts_block_about1">
    <div class="prelatife container text-center">
      <div class="insides">
        <p><?php echo $this->setting['career_hero_subtitle'] ?></p>
        <div class="clear"></div>
      </div>
    </div>
  </section>

  <section class="blocks_middle_store2 default_sc pg_contact">
    <div class="prelatife container">
      <div class="clear height-50"></div>
      <div class="content-text text-center maw750 tengah">
        <?php echo $this->setting['career_content'] ?>
        <!-- <div class="clear height-20"></div> -->
        <?php //echo $this->renderPartial('//home/_form_contact3', array('model' => $model)); ?>

        <div class="clear"></div>
      </div>

      <div class="clear height-50"></div>
      <div class="clear height-25"></div>
    </div>

  </section>

  <div class="clear"></div>
</div>

admin/protected/views/home/designhome.php
<div class="container">
    <div class="slide-home">
        <div class="flexslider">
            <ul class="slides">
                <li>
                    <img class="img-responsive" src="<?php echo Yii::app()->baseUrl ?>/images/slide/slide-1.jpg" alt="Slide UBS Style">
                    <div class="slides-container">
                        <div class="line-slide"></div>
                        <h3>THE AXEL VINESSE COLLECTION</h3>
                        <div class="line-slide"></div>
                        <div class="height-30"></div>
                        <p>
                            A PLAYFUL CONTEMPORARY DESIGN <br>
                            COMBINING ETNICAL BOLDNESS WITH <br>
                            A PEEK OF THE FUTURE LIFESTYLE
                        </p>
                        <div class="height-20"></div>
                        <p>
                            <a class="button-border-black inverse" style="width: 180px;" href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">BROWSE JEWELRY</a> <br>
                        </p>
                        <p>
                            <a class="button-border-black inverse" style="width: 180px;" href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">VIEW PRODUCT</a>
                        </p>
                    </div>
                </li>
                <li>
                    <img class="img-responsive" src="<?php echo Yii::app()->baseUrl ?>/images/slide/slide-1.jpg" alt="Slide UBS Style">
                </li>
            </ul>
        </div>
    </div>
<?php
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/asset/js/FlexSlider/jquery.flexslider-min.js',CClientScript::POS_END);
Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/asset/js/FlexSlider/flexslider.css');
?>
<script type="text/javascript">
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    controlNav: false,
  });
});
</script>
    <div class="category-banner-home">
        <div class="row">
            <div class="col-sm-4">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>"><img src="<?php echo Yii::app()->baseUrl ?>/asset/images/thumb-category-woman.jpg" alt="category woman UBS Style" class="img-responsive"></a>
            </div>
            <div class="col-sm-4">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>"><img src="<?php echo Yii::app()->baseUrl ?>/asset/images/thumb-category-man.jpg" alt="category man UBS Style" class="img-responsive"></a>
            </div>
            <div class="col-sm-4">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>"><img src="<?php echo Yii::app()->baseUrl ?>/asset/images/thumb-category-kids.jpg" alt="category kids UBS Style" class="img-responsive"></a>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="container-by-brand">
        <div class="row">
            <div class="col-md-6">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>"><img src="<?php echo Yii::app()->baseUrl ?>/asset/images/thumb-category-youth.jpg" alt="category kids UBS Style" class="img-responsive"></a>
            </div>
            <div class="col-md-6">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>"><img class="img-responsive" src="<?php echo Yii::app()->baseUrl ?>/asset/images/shop-by-brand.jpg" alt="Shop By Brand UBS Style"></a>
            </div>
        </div>
    </div>
    <div class="height-30"></div>
    <div class="line-grey"></div>
    <div class="height-30"></div>
    <div class="gift-lifestyle">
        <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>"><img class="img-responsive" src="<?php echo Yii::app()->baseUrl ?>/asset/images/lifestyle-gift-items.jpg" alt="Shop By Brand UBS Style"></a>
    </div>
    <div class="height-20"></div>
    <div class="sub-content-header">
        <div class="height-10"></div>
        <div class="line-grey"></div>
        <div class="title">
            <h3>LIFESTYLE BLOG</h3>
        </div>
    </div>
    <div class="height-20"></div>
    <div class="container-lifestyle-blog-home">
        <div class="col-md-3 col-sm-6">
            <div class="image-blog-home">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">
                    <img src="<?php echo Yii::app()->baseUrl ?>/images/blog/blog-raisya.jpg" alt="Blog Raisya UBS Style">
                </a>
            </div>
            <div class="blog-desc-home">
                <h3><a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Model minute: Tips cantik ala Raisa untuk daily activity!</a></h3>
                <p>Jul 21, 2014 - <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Beauty Stars</a></p>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="image-blog-home">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">
                    <img src="<?php echo Yii::app()->baseUrl ?>/images/blog/blog-sepatu-bulu.jpg" alt="Blog Raisya UBS Style">
                </a>
            </div>
            <div class="blog-desc-home">
                <h3><a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Wow! Sepatu baru Louboutin bertabur bulu Ostritch!</a></h3>
                <p>Jul 21, 2014 - <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Beauty Stars</a></p>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="image-blog-home">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">
                    <img src="<?php echo Yii::app()->baseUrl ?>/images/blog/blog-pallete.jpg" alt="Blog Raisya UBS Style">
                </a>
            </div>
            <div class="blog-desc-home">
                <h3><a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Masquerade party? How to “still” look fabulous with nude pallete.</a></h3>
                <p>Jul 21, 2014 - <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Beauty Stars</a></p>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="image-blog-home">
                <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">
                    <img src="<?php echo Yii::app()->baseUrl ?>/images/blog/blog-model.jpg" alt="Blog Raisya UBS Style">
                </a>
            </div>
            <div class="blog-desc-home">
                <h3><a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">2015 Trends is going to be ethnically Epic!</a></h3>
                <p>Jul 21, 2014 - <a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Beauty Stars</a></p>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <p style="text-align: center;">
        <a class="button-border-black" href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">VIEW ALL ARTICLE</a>
    </p>
</div>

admin/protected/views/home/katalog.php
<section class="default_sc top_inside_pg_default">
  <div class="out_table">
    <div class="in_table">
      <div class="prelatife container">
        <h1 class="sub_titlepage">Download Katalog</h1>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</section>
<section class="default_sc insides_middleDefaultpages back-white">
  <div class="prelatife container">
    <div class="clear height-50"></div><div class="height-5"></div>
    <div class="content-text text-center">
        <p>Katalog versi online dapat diunduh di bawah ini untuk kenyamanan para pelanggan perabotplastik.com</p>
        <div class="clear height-15"></div>
        <div class="list_downloads_item">
          <ul class="list-inline">
            <?php foreach ($dataPdf as $key => $value): ?>
              
            <li>
              <div class="items">
                <div class="picts"><a href="<?php echo Yii::app()->baseUrl ?>/images/pdf/<?php echo $value->file ?>" class="" download><img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(233,295, '/images/pdf/'.$value->image , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="" class="img-responsive"></a></div>
                <div class="clear height-15"></div>
                <div class="desc">
                  <span class="names"><?php echo $value->nama ?></span>
                  <div class="clear"></div>
                  <a href="<?php echo Yii::app()->baseUrl ?>/images/pdf/<?php echo $value->file ?>" class="download btn btn-link" download><img src="<?php echo $this->assetBaseurl; ?>icon-katalog_pdf-download.png" alt="" class="inline-pict"> &nbsp;&nbsp;Download</a>
                  <div class="clear"></div>
                </div>
              </div>
            </li>
            <?php endforeach ?>
          </ul>
          <div class="clear"></div>
        </div>
        <!-- end list download item -->
        <div class="clear height-40"></div>

        <div class="clear height-30"></div>
      <div class="clear"></div>
    </div>

    <div class="clear"></div>
  </div>
</section>

admin/protected/views/home/lokasi.php
<div class="outer-middle">
	<div class="prelatif container">
			<div class="fcs-wrap region h222 prelatif">
				<div class="ill-page-inside"><img src="<?php echo Yii::app()->baseUrl; ?>/asset/images/ill-contact2.jpg" alt="ill Contact cheetam salt"></div>
				<div class="clearfix"></div>
			</div>
			<div class="clear height-15"></div>
			<div class="height-1"></div>
			<div class="region inside-content prelatif">
				<div class="clear height-5"></div>
				<div class="height-2"></div>

				<div class="left left-content-ins margin-right-35">
					<div class="ins">
						<h2 class="title"><?php echo Yii::t('main', 'contact us') ?></h2>
						<div class="clear height-10"></div>
						<div class="lines-blue"></div>
						<div class="clear height-5"></div>

						<div class="menu-inside">
							<ul>
								<li><a href="<?php echo CHtml::normalizeUrl(array('home/contact', 'lang'=>Yii::app()->language)); ?>"><?php echo Yii::t('main', 'hubungi kami') ?></a></li>
								<li class="separator"></li>
								<li class="active"><a href="<?php echo CHtml::normalizeUrl(array('home/lokasikami', 'lang'=>Yii::app()->language)); ?>"><?php echo Yii::t('main', 'lokasi kami') ?></a></li>
								<li class="separator"></li>
							</ul>
						</div>

						<div class="clear"></div>
					</div>
				</div>
				<div class="left right-content">
						<div class="clear height-20"></div>
						<div class="right breadcumb"><a href="<?php echo CHtml::normalizeUrl(array('home/index', 'lang'=>Yii::app()->language)); ?>"><?php echo Yii::t('main', 'home') ?></a> &gt; <b><?php echo Yii::t('main', 'lokasi kami') ?></b></div>
						<div class="clear height-25"></div>
						<div class="content-text">
							
							<div class="lokasi-block">
								<div class="row">
									<?php foreach ($data as $key => $value): ?>
									<div class="col-xs-4">
										<div class="item">
											<div class="title"><?php echo $value->title ?></div>
											<div class="clear height-25"></div>
											<p><?php echo nl2br(trim($value->content)) ?><br>
											<?php if ($value->peta_google != ''): ?>
											<span class="glyphicon glyphicon-search"></span> 
											<a href="<?php echo $value->peta_google ?>" target="_blank">Lihat peta</a>
											<?php endif ?>
											</p>
											<p>Phone&nbsp;&nbsp; &nbsp;: <?php echo $value->phone ?><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $value->phone2 ?><br />
Fax&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; : <?php echo $value->fax ?><br />
E-mail&nbsp;&nbsp; &nbsp;: <a href="mailto:<?php echo $value->email ?>"><?php echo $value->email ?></a></p>
										</div>
									</div>
									<?php if ((($key + 1) % 3) == 0): ?>
									<div class="clear height-20"></div>
									<?php endif ?>
									<?php endforeach ?>

								</div>
							</div>
							
							<div class="clear height-20"></div>
							<div class="clear"></div>
						</div>

					<div class="clearfix"></div>
				</div>
				<div class="clear"></div>
			</div>

			<div class="clear height-10"></div>
			<div class="height-2"></div>
			
		<div class="clearfix"></div>
	</div>
	<div class="clear"></div>
</div>