admin/protected/controllers/MemberController.php
<?php

class MemberController extends Controller
{

	public function actionIndex()
	{
		$session = new CHttpSession;
		$session->open();
		if (isset($session['login_member'])) {
			$model = MeMember::model()->findByPk($session['login_member']['id']);
			if(isset($_POST['MeMember'])) {
				$pass = $model->pass;
				$model->attributes = $_POST['MeMember'];
				if ($_POST['MeMember']['passold'] != '') {
					$model->scenario = 'updatePass';
					$model->pass = sha1($model->pass);
					$model->pass2 = sha1($model->pass2);
				}else{
					$model->scenario = 'update';
					$model->pass = $pass;
				}
				if ($model->validate()) {
					if ($_POST['MeMember']['passold'] != '') {
						if (sha1($model->passold) != $pass) {
							$model->addError('passold','Password lama tidak valid');
						}
					}
					if(!$model->hasErrors())
					{
						$model->save();
						$this->redirect(array());
					}
				}
			}

			$model->pass = '';
			$model->pass2 = '';
			$model->passold = '';

			$criteria = new CDbCriteria;
			$criteria->addCondition('email = :email');
			$criteria->order = 'date_modif DESC';
			$criteria->params[':email'] = $session['login_member']['email'];
			$order =  new CActiveDataProvider('OrOrder', array(
				'criteria'=>$criteria,
				'pagination'=>array(
			        'pageSize'=>10,
			    ),
			));
			$this->layout='//layouts/column2';
			$this->render('index2', array(
				'model'=>$model,
				'order'=>$order,
			));	
		}else{
			$model = new MeMember;
			$model->scenario = 'createMember';
			
			$modelLogin = new LoginForm2;

			if(isset($_POST['MeMember']))
			{
				$model->attributes = $_POST['MeMember'];

				if ($model->validate()) {
					$transaction=$model->dbConnection->beginTransaction();
					try
					{
						$model->aktif = 1;
						$pass = $model->pass;
						$model->pass = sha1($model->pass);
						$model->pass2 = sha1($model->pass2);
						$model->save();

						$transaction->commit();

						$mail = $this->renderPartial('//mail/register', array(
							'model' => $model,
						), true);

						$config = array(
							'to'=>array($model->email, $this->setting['email'], $this->setting['contact_email']),
							// 'to'=>array($model->email),
							'subject'=>'['.Yii::app()->name.'] Register '.$model->email,
							'message'=>$mail,
						);
						// kirim email
						Common::mail($config);

						Yii::app()->user->setFlash('success','Registration success');
						$session['login_member'] = $model->attributes;
					    if ($_GET['ret']) {
							$this->redirect(urldecode($_GET['ret']));
					    }else{
							$this->redirect(array('index'));
					    }
					}
					catch(Exception $ce)
					{
					    $transaction->rollback();
					}
				}
			}
			if(isset($_POST['LoginForm2']) AND $_POST['type']=='aktifkan')
			{
				$modelLogin->attributes=$_POST['LoginForm2'];
				$memberData = MeMember::model()->find('acc_number = :acc_number', array(':acc_number'=>$modelLogin->username));
				// validate user input and redirect to the previous page if valid
				if ($memberData != null) {
					$hash = urlencode(base64_encode($memberData->email.'|'.rand(1000000,10000000)));
					$mail = $this->renderPartial('//mail/aktifkan', array(
						'hash'=>$hash,
						'email'=>$memberData->email,
					), true);
					// echo $mail;
					// exit;

					$config = array(
						'to'=>array($memberData->email),
						// 'to'=>array($model->email),
						'subject'=>'['.Yii::app()->name.'] Pengaktifan Akun',
						'message'=>$mail,
					);
					// kirim email
					Common::mail($config);
					Yii::app()->user->setFlash('success','Please access your email to activated your account');
					$this->redirect(array('index'));
				}
			}elseif(isset($_POST['LoginForm2']) AND $_POST['type']=='login'){
				$modelLogin->attributes=$_POST['LoginForm2'];
				// validate user input and redirect to the previous page if valid
				if($modelLogin->validate()){
					$data = MeMember::model()->find('email = :email', array(':email'=>$modelLogin->username));
					$session['login_member'] = $data->attributes;
				    if ($_GET['ret']) {
						$this->redirect(urldecode($_GET['ret']));
				    }else{
						$this->redirect(array('index'));
				    }
				}
			}

			// $this->pageTitle = 'Login & Register - '.$this->pageTitle;
			// $this->layout='//layouts/home';
			$this->layout='//layouts/column2';
			$this->render('index', array(
				'model'=>$model,
				'modelLogin'=>$modelLogin,
				// 'modelDelivery'=>$modelDelivery,
			));	
		}
	}
	public function actionLogout()
	{
		$session = new CHttpSession;
		$session->open();
		unset($session['login_member']);
		$this->redirect(array('index'));
	}

	public function actionVieworder($nota)
	{
		$session = new CHttpSession;
		$session->open();
		$modelOrder = OrOrder::model()->find('CONCAT(`invoice_prefix`, "-", `invoice_no`) = :nota AND email  = :email ', array(':nota'=>$nota, ':email'=>$session['login_member']['email']));

		if (is_null($modelOrder))
			throw new CHttpException(404,'The requested page does not exist.');

		$data = OrOrderProduct::model()->findAll('order_id = :order_id', array(':order_id'=>$modelOrder->id));

		$this->pageTitle = 'View Order - '.$this->pageTitle;
		$this->layout='//layouts/column2';
		// $this->renderPartial('/mail/cart2', array(
		// 	'data' => $data,
		// 	'modelOrder' => $modelOrder,
		// ));
		$this->render('vieworder', array(
			'data' => $data,
			'modelOrder' => $modelOrder,
		));
	}

	public function actionForgot()
	{
		$modelLogin = new LoginForm2;

		if(isset($_POST['LoginForm2']))
		{
			$modelLogin->attributes=$_POST['LoginForm2'];
			// validate user input and redirect to the previous page if valid
			if ($modelLogin->username != '') {
				$hash = urlencode(base64_encode($modelLogin->username.'|'.rand(1000000,10000000)));
				$mail = $this->renderPartial('//mail/forgotpass', array(
					'hash'=>$hash,
					'email'=>$modelLogin->username,
				), true);
				// echo $mail;
				// exit;

				$config = array(
					'to'=>array($modelLogin->username),
					// 'to'=>array($model->email),
					'subject'=>'['.Yii::app()->name.'] Forgot Password',
					'message'=>$mail,
				);
				// kirim email
				Common::mail($config);
				Yii::app()->user->setFlash('success','Please access your email to reset your password');
				$this->redirect(array('index'));
			}
		}

		// $this->pageTitle = 'Login & Register - '.$this->pageTitle;
		// $this->layout='//layouts/home';
		$this->layout='//layouts/column2';
		$this->render('forgot', array(
			'modelLogin'=>$modelLogin,
			// 'modelDelivery'=>$modelDelivery,
		));	
	}
	public function actionChangepass($hash)
	{
		$email = explode('|', base64_decode(urldecode($hash)));
		$email = $email[0];
		
		$model = MeMember::model()->find('email = :email', array(':email'=>$email));

		if(isset($_POST['MeMember'])) {
			$pass = $model->pass;
			$model->attributes = $_POST['MeMember'];
			if ($_POST['MeMember']['pass'] != '') {
				$model->scenario = 'updatePass';
				$model->pass = sha1($model->pass);
				$model->pass2 = sha1($model->pass2);
			}
			if ($model->validate()) {
				if(!$model->hasErrors())
				{
					$model->save();
					Yii::app()->user->setFlash('success','Your password has been changed , please login');
					$this->redirect(array('index'));
				}
			}
		}
		$model->pass = '';
		$model->pass2 = '';

		// $this->pageTitle = 'Login & Register - '.$this->pageTitle;
		// $this->layout='//layouts/home';
		$this->layout='//layouts/column2';
		$this->render('changepass', array(
			'model'=>$model,
			// 'modelDelivery'=>$modelDelivery,
		));	
	}
	public function actionAktifkan($hash)
	{
		$email = explode('|', base64_decode(urldecode($hash)));
		$email = $email[0];
		
		$model = MeMember::model()->find('email = :email', array(':email'=>$email));

		if(isset($_POST['MeMember'])) {
			$pass = $model->pass;
			$model->attributes = $_POST['MeMember'];
			if ($_POST['MeMember']['pass'] != '') {
				$model->scenario = 'updatePass';
				$model->pass = sha1($model->pass);
				$model->pass2 = sha1($model->pass2);
			}
			if ($model->validate()) {
				if(!$model->hasErrors())
				{
					$model->save();
					Yii::app()->user->setFlash('success','Your password has been changed , please login');
					$this->redirect(array('index'));
				}
			}
		}
		$model->pass = '';
		$model->pass2 = '';

		// $this->pageTitle = 'Login & Register - '.$this->pageTitle;
		// $this->layout='//layouts/home';
		$this->layout='//layouts/column2';
		$this->render('aktifkan', array(
			'model'=>$model,
			// 'modelDelivery'=>$modelDelivery,
		));	
	}

}

admin/protected/views/member/aktifkan.php
<div class="clear"></div>
<div class="subpage product">

  <div class="prelatife container">

    <div class="clear height-45"></div>
    <div class="back_product bloc_breadcrumb">
      <ol class="breadcrumb">
        <li><a href="<?php echo CHtml::normalizeUrl(array('/home/index')); ?>">Home</a></li>
        <li class="active">Cart</li>
      </ol>
      <div class="clear"></div>
    </div>


    <div class="outer-cont-carts"> 
        <div class="clear height-20"></div>


	<!-- /. Start Content About -->
	<div class="inside-content">
		<div class="m-ins-content m-ins-myaccount">
			<?php if(Yii::app()->user->hasFlash('success')): ?>
			
			    <?php $this->widget('bootstrap.widgets.TbAlert', array(
			        'alerts'=>array('success'),
			    )); ?>
			
			<?php endif; ?>
			<div class="margin-15">
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'login-form',
    'type'=>'horizontal',
    // 'action'=>array('index'),
    //'htmlOptions'=>array('class'=>'well'),
	'enableClientValidation'=>false,
	'clientOptions'=>array(
		'validateOnSubmit'=>false,
	),
)); ?>
					<div class="box-account-history">
						<div class="center">
							<div class="clear height-30"></div>
							<p>Enter your new password to access <?php echo Yii::app()->name ?>.</p>
							<div class="clear height-30"></div>
							<div class="basic-information form-horizontal col-md-6" style="margin: 0px auto; float: none;">
								<?php echo CHtml::errorSummary($model, '', '', array('class'=>'alert alert-danger')); ?>
								<div class="form-group">
									<?php echo $form->labelEx($model, 'pass', array('class'=>'control-label col-sm-4')) ?>
								    <div class="col-sm-5">
								    	<?php echo $form->passwordField($model, 'pass', array('class'=>'form-control')) ?>
								    </div>
								</div>

								<?php echo CHtml::errorSummary($model, '', '', array('class'=>'alert alert-danger')); ?>
								<div class="form-group">
									<?php echo $form->labelEx($model, 'pass2', array('class'=>'control-label col-sm-4')) ?>
								    <div class="col-sm-5">
								    	<?php echo $form->passwordField($model, 'pass2', array('class'=>'form-control')) ?>
								    </div>
								</div>
							 
							    <div class="form-group">
								    <label class="col-sm-4 control-label" for="input"></label>
								    <div class="col-sm-8" style="text-align: left;">
								    	<button type="submit" class="btn back-btn-primary-gold">SUBMIT</button>
								    </div>
							    </div>
							</div>
						</div>
						
					</div>
<?php $this->endWidget(); ?>

			</div>
			<div class="height-30"></div>
			<div class="height-30"></div>

			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
	<!-- /. End Content About -->


        <div class="clear height-50"></div><div class="height-20"></div>
            <div class="clear"></div>
    </div>


    <div class="clear"></div>
  </div>
</div>

admin/protected/views/member/changepass.php
<div class="clear"></div>
<div class="subpage product">

  <div class="prelatife container">

    <div class="clear height-45"></div>
    <div class="back_product bloc_breadcrumb">
      <ol class="breadcrumb">
        <li><a href="<?php echo CHtml::normalizeUrl(array('/home/index')); ?>">Home</a></li>
        <li class="active">Cart</li>
      </ol>
      <div class="clear"></div>
    </div>


    <div class="outer-cont-carts"> 
        <div class="clear height-20"></div>


	<!-- /. Start Content About -->
	<div class="inside-content">
		<div class="m-ins-content m-ins-myaccount">
			<?php if(Yii::app()->user->hasFlash('success')): ?>
			
			    <?php $this->widget('bootstrap.widgets.TbAlert', array(
			        'alerts'=>array('success'),
			    )); ?>
			
			<?php endif; ?>
			<div class="margin-15">
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'login-form',
    'type'=>'horizontal',
    // 'action'=>array('index'),
    //'htmlOptions'=>array('class'=>'well'),
	'enableClientValidation'=>false,
	'clientOptions'=>array(
		'validateOnSubmit'=>false,
	),
)); ?>
					<div class="box-account-history">
						<div class="center">
							<div class="clear height-30"></div>
							<p>Enter your new password to access <?php echo Yii::app()->name ?>.</p>
							<div class="clear height-30"></div>
							<div class="basic-information form-horizontal col-md-6" style="margin: 0px auto; float: none;">
								<?php echo CHtml::errorSummary($model, '', '', array('class'=>'alert alert-danger')); ?>
								<div class="form-group">
									<?php echo $form->labelEx($model, 'pass', array('class'=>'control-label col-sm-4')) ?>
								    <div class="col-sm-5">
								    	<?php echo $form->passwordField($model, 'pass', array('class'=>'form-control')) ?>
								    </div>
								</div>

								<?php echo CHtml::errorSummary($model, '', '', array('class'=>'alert alert-danger')); ?>
								<div class="form-group">
									<?php echo $form->labelEx($model, 'pass2', array('class'=>'control-label col-sm-4')) ?>
								    <div class="col-sm-5">
								    	<?php echo $form->passwordField($model, 'pass2', array('class'=>'form-control')) ?>
								    </div>
								</div>
							 
							    <div class="form-group">
								    <label class="col-sm-4 control-label" for="input"></label>
								    <div class="col-sm-8" style="text-align: left;">
								    	<button type="submit" class="btn back-btn-primary-gold">SUBMIT</button>
								    </div>
							    </div>
							</div>
						</div>
						
					</div>
<?php $this->endWidget(); ?>

			</div>
			<div class="height-30"></div>
			<div class="height-30"></div>

			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
	<!-- /. End Content About -->


        <div class="clear height-50"></div><div class="height-20"></div>
            <div class="clear"></div>
    </div>


    <div class="clear"></div>
  </div>
</div>

admin/protected/views/member/forgot.php
<div class="subpage product">

  <div class="prelatife container">

    <div class="clear height-45"></div>
    <div class="back_product bloc_breadcrumb">
      <ol class="breadcrumb">
        <li><a href="<?php echo CHtml::normalizeUrl(array('/home/index')); ?>">Home</a></li>
        <li class="active">Forgot Password</li>
      </ol>
      <div class="clear"></div>
    </div>


    <div class="outer-cont-carts"> 
        <div class="clear height-20"></div>


	<!-- /. Start Content About -->
	<div class="inside-content">
		<div class="m-ins-content m-ins-myaccount">
			<?php if(Yii::app()->user->hasFlash('success')): ?>
			
			    <?php $this->widget('bootstrap.widgets.TbAlert', array(
			        'alerts'=>array('success'),
			    )); ?>
			
			<?php endif; ?>
			<div class="margin-15">
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'login-form',
    'type'=>'horizontal',
    // 'action'=>array('index'),
    //'htmlOptions'=>array('class'=>'well'),
	'enableClientValidation'=>false,
	'clientOptions'=>array(
		'validateOnSubmit'=>false,
	),
)); ?>
					<div class="box-account-history">
						<div class="center">
							<div class="height-50"></div>
							<div class="height-10"></div>
							<p>Enter your email address to recover / reset your forgotten password</p>
							<?php echo CHtml::errorSummary($modelLogin, '', '', array('class'=>'alert alert-danger')); ?>
							<div class="clear height-30"></div>
							<!-- <img src="<?php echo Yii::app()->baseUrl ?>/asset/images/mail.gif" alt=""> -->
					    	<?php echo $form->textField($modelLogin, 'username', array('class'=>'form-control', 'style'=>'display: inline-block; width: auto; height: 30px;')) ?>
					    	<button type="submit" class="btn back-btn-primary-gold">SUBMIT</button>
						</div>
						 

					</div>
<?php $this->endWidget(); ?>

			</div>
			<div class="height-50"></div>
			<div class="height-50"></div>

			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
	<!-- /. End Content About -->


        <div class="clear height-50"></div><div class="height-20"></div>
            <div class="clear"></div>
    </div>


    <div class="clear"></div>
  </div>
</div>

admin/protected/views/member/index2.php
<div class="subpage product">

  <div class="prelatife container">

    <div class="clear height-45"></div>
    <div class="back_product bloc_breadcrumb">
      <ol class="breadcrumb">
        <li><a href="<?php echo CHtml::normalizeUrl(array('/home/index')); ?>">Home</a></li>
        <li class="active">Member Dashboard</li>
      </ol>
      <div class="clear"></div>
    </div>


    <div class="outer-cont-carts"> 
        <div class="clear height-20"></div>



    <div class="inside-content">
        <!-- /. Start Content About -->
        <div class="m-ins-content m-ins-myaccount">
            <?php if(Yii::app()->user->hasFlash('success')): ?>
            
                <?php $this->widget('bootstrap.widgets.TbAlert', array(
                    'alerts'=>array('success'),
                )); ?>
            
            <?php endif; ?>
            
            <div class="margin-15">
            <div class="row">
                <div class="col-xs-6">
                    <div class="padding-right-40">
                        <div class="box-account-history w519">
                            <h1 class="title-inside-page">Order History</h1>
                            <div class="clear height-30"></div>
                            
                                <table class="table table-striped tb-history-account">
                                    <?php foreach ($order->getData() as $key => $value): ?>
                                    <tr>
                                        <td>
                                            <b><?php echo $value->invoice_prefix.'-'.$value->invoice_no ?> (<?php echo OrOrderStatus::model()->findByPk($value->order_status_id)->name ?>)</b> <br>
                                            Tanggal Transaksi: <b><?php echo date('d F Y', strtotime($value->date_add)) ?></b> <br>
                                            Total: <b><?php echo Cart::money($value->total+$value->delivery_price, 0) ?></b>
                                        </td>
                                        <td><a href="<?php echo CHtml::normalizeUrl(array('/member/vieworder', 'nota'=>$value->invoice_prefix.'-'.$value->invoice_no)); ?>"><i class="fa fa-search fa-2x"></i></a></td>
                                    </tr>
                                    <?php endforeach ?>
                                </table>
                                <?php $this->widget('CLinkPager', array(
                                    'pages' => $order->getPagination(),
                                )) ?>

                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'user-form',
    'type'=>'horizontal',
    //'htmlOptions'=>array('class'=>'well'),
    'enableClientValidation'=>false,
    'clientOptions'=>array(
        'validateOnSubmit'=>false,
    ),
)); ?>
                    <div class="box-infomation-account w358">
                        <h1 class="title-inside-page">Account Information</h1>
                        <div class="clear height-30"></div>
                        
                        <div class="basic-information">

                                <?php echo CHtml::errorSummary($model, '', '', array('class'=>'alert alert-danger')); ?>


                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'passold', array('class'=>'col-sm-4 control-label')); ?>
                                    <div class="col-sm-5">
                                    <?php echo $form->passwordField($model, 'passold', array('class'=>'form-control')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'pass', array('class'=>'col-sm-4 control-label')); ?>
                                    <div class="col-sm-5">
                                    <?php echo $form->passwordField($model, 'pass', array('class'=>'form-control')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'pass2', array('class'=>'col-sm-4 control-label')); ?>
                                    <div class="col-sm-5">
                                    <?php echo $form->passwordField($model, 'pass2', array('class'=>'form-control')); ?>
                                    </div>
                                </div>

                         </div>

                         <div class="clear height-0"></div>
                         <div class="lines-grey"></div>
                         <div class="clear height-20"></div>
                         <div class="height-2"></div>

                         <div class="basic-information">
                            <h1 class="title-inside-page">Delivery Information</h1>
                            <div class="clear height-25"></div>

                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'first_name', array('class'=>'control-label col-sm-4')) ?>
                                    <div class="col-sm-5">
                                        <?php echo $form->textField($model, 'first_name', array('class'=>'form-control')) ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'last_name', array('class'=>'control-label col-sm-4')) ?>
                                    <div class="col-sm-5">
                                        <?php echo $form->textField($model, 'last_name', array('class'=>'form-control')) ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'hp', array('class'=>'control-label col-sm-4')) ?>
                                    <div class="col-sm-5">
                                        <?php echo $form->textField($model, 'hp', array('class'=>'form-control')) ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'address', array('class'=>'control-label col-sm-4')) ?>
                                    <div class="col-sm-5">
                                        <?php echo $form->textField($model, 'address', array('class'=>'form-control')) ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'province', array('class'=>'control-label col-sm-4')) ?>
                                    <div class="col-sm-5">
                                        <?php echo $form->textField($model, 'province', array('class'=>'form-control')) ?>
                                        <?php //echo $form->dropDownList($model, 'province',CHtml::listData(City::model()->findAll('1 GROUP BY province_id'),'province_id', 'province'), array('class'=>'form-control', 'empty'=>'Select State')) ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $form->labelEx($model, 'city', array('class'=>'control-label col-sm-4')) ?>
                                    <div class="col-sm-5">
                                        <?php echo $form->textField($model, 'city', array('class'=>'form-control')) ?>
                                        <?php //echo $form->dropDownList($model, 'city', array(), array('class'=>'form-control', 'empty'=>'Select City')) ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-4 control-label" for="input"></label>
                                    <div class="col-sm-5">
                                        <button type="submit" class="btn btn-primary">EDIT</button>
                                    </div>
                                </div>


                         </div>

                    </div>
<?php $this->endWidget(); ?>
                </div>
            </div>
            </div>

            <div class="clear height-25"></div>

            <div class="clear"></div>
        </div>
        <!-- /. End Content About -->



        <div class="clear height-50"></div><div class="height-20"></div>
            <div class="clear"></div>
    </div>


    <div class="clear"></div>
  </div>
</div>