admin/protected/models/Blog.php
<?php

/**
 * This is the model class for table "blog".
 *
 * The followings are the available columns in table 'blog':
 * @property integer $id
 * @property string $image
 * @property integer $active
 * @property string $date_input
 * @property string $date_update
 * @property string $insert_by
 * @property string $last_update_by
 */
class Blog extends CActiveRecord
{
	public $title;
	public $content;
	public $writer_name;
	public $writer_image;
	public $writer_avatar;
	public $year;
	public $month;

	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Blog the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'pg_blog';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('image, active', 'required'),
			array('active, topik_id', 'numerical', 'integerOnly'=>true),
			array('writer, image, insert_by, last_update_by', 'length', 'max'=>255),
			// array('image', 'file', 'types'=>'jpg, gif, png', 'allowEmpty'=>FALSE, 'on'=>'insert'),
			// array('image', 'file', 'types'=>'jpg, gif, png', 'allowEmpty'=>TRUE, 'on'=>'update'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('title, writer_name ,id, active, date_input, date_update, insert_by, last_update_by', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'images'=>array(self::HAS_MANY, 'BlogImage', 'blog_id'),
			'description'=>array(self::HAS_ONE, 'BlogDescription', 'blog_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Title',
			'writer_name' => 'writer_name',
			'active' => 'Status',
			'date_input' => 'Date Input',
			'date_update' => 'Date Update',
			'insert_by' => 'Insert By',
			'last_update_by' => 'Last Update By',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search($language_id)
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->select = "t.*, pg_blog_description.title";
		$criteria->join = "
		LEFT JOIN pg_blog_description ON pg_blog_description.blog_id=t.id
		";
		$criteria->addCondition('pg_blog_description.language_id = :language_id');
		$criteria->params = array(':language_id'=>$language_id);

		$criteria->compare('id',$this->id);
		$criteria->compare('active',$this->active);
		$criteria->compare('date_input',$this->date_input,true);
		$criteria->compare('date_update',$this->date_update,true);
		$criteria->compare('insert_by',$this->insert_by,true);
		$criteria->compare('last_update_by',$this->last_update_by,true);

		$criteria->compare('title',$this->title, true);
		$criteria->compare('pastor_description.title',$this->writer_name, true);

		$criteria->order = "date_input DESC";

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function getData($id, $languageId=1)
	{
		$criteria=new CDbCriteria;

		$criteria->select = "t.*, pg_blog_description.title, pg_blog_description.content";
		$criteria->join = "
		LEFT JOIN pg_blog_description ON pg_blog_description.blog_id=t.id
		";
		$criteria->addCondition('pg_blog_description.language_id = :language_id');
		$criteria->addCondition('t.id = :id');
		$criteria->params = array(
			':language_id'=>$languageId,
			':id'=>$id,
		);

		$model = Blog::model()->find($criteria);

		return $model;
	}

	public function getDataDesc($id, $languageId=1)
	{
		$criteria=new CDbCriteria;

		$criteria->addCondition('language_id = :language_id');
		$criteria->addCondition('blog_id = :id');
		$criteria->params = array(
			':language_id'=>$languageId,
			':id'=>$id,
		);

		$model = BlogDescription::model()->find($criteria);

		return $model;
	}

	public function getAllData($limit = false, $id = false, $languageId=1)
	{
		// default
		$pageTitle = 'All';
		$title = 'Semua Artikel';

		$criteria=new CDbCriteria;

		$criteria->select = "t.*, pg_blog_description.title, pg_blog_description.content";

		$criteria->join = "
		LEFT JOIN pg_blog_description ON pg_blog_description.blog_id=t.id
		";

		$params = array();

		if ($id !== false) {
			$criteria->limit = $limit;
			$criteria->addCondition('t.id != :id');
			$params[':id'] = $id;
		}
		// if ($_GET['q'] != '') {
		// 	$criteria->addCondition('(pg_blog_description.content LIKE :q OR pg_blog_description.title LIKE :q)');
		// 	$params[':q'] = '%'.$_GET['q'].'%';

		// }
		if ($_GET['topik'] != '') {
			$categoryData = Category::model()->find('slug = :slug',array(':slug'=>$_GET['topik']));
			$criteria->addCondition('t.topik_id = :topik');
			$params[':topik'] = $categoryData->id;

			$pageTitle = 'Topik '. $categoryData->name;
			$title = $categoryData->name;
		}
		if ($_GET['month'] != '' AND $_GET['year'] != '') {
			$criteria->addCondition('MONTH(t.date_input) = :month');
			$criteria->addCondition('YEAR(t.date_input) = :year');
			$params[':month'] = $_GET['month'];
			$params[':year'] = $_GET['year'];
		}

		$criteria->addCondition('pg_blog_description.language_id = :language_id');
		$criteria->addCondition('t.`active` = 1');
		$params[':language_id'] = $languageId;
		if($_GET['order'] == 'from-a') {
			$criteria->order = "pg_blog_description.title ASC";
		} elseif($_GET['order'] == 'from-z') {
			$criteria->order = "pg_blog_description.title DESC";
		} elseif($_GET['order'] == 'rand') {
			$criteria->order = "RAND()";
		} else {
			$criteria->order = "date_input DESC";
		}
		
		$criteria->params = $params;

		// mengambil jumlah data
		$jml = $this->count($criteria);

		// pagination
		$pages=new CPagination($jml);
		
		$pages->pageSize=$limit;
		if ($_GET['perpage'] != '' AND $limit == false) {
			$pages->pageSize=$_GET['perpage'];
		}
    	$pages->applyLimit($criteria);

		$data = $this->findAll($criteria);

		$result = array(
			'pageTitle'=>$pageTitle,
			'title'=>$title,
			'jml'=>$jml,
			'data'=>$data,
			'categoryId'=>$categoryId,
			'pages'=>$pages,
			// 'strRefine'=>implode(', ', $strRefine),
		);

		return $result;
	}

	public function getAllDataByDate($writer = false, $month, $year, $limit = false, $id = false, $languageId=1)
	{
		$criteria=new CDbCriteria;

		$criteria->select = "t.*, pg_blog_description.title";
		$criteria->join = "
		LEFT JOIN pg_blog_description ON pg_blog_description.blog_id=t.id
		";

		$params = array();

		if ($id !== false) {
			$criteria->limit = $limit;
			$criteria->addCondition('t.id != :id');
			$params[':id'] = $id;
		}

		$criteria->addCondition('pg_blog_description.language_id = :language_id');
		$criteria->addCondition('t.`active` = 1');

		if ($writer != '') {
			$criteria->addCondition('t.writer = :writer');
			$params[':writer'] = $writer;
		}else{
			if ($month != '' AND $year != '') {
				$criteria->addCondition('MONTH(t.date_input) = :month');
				$criteria->addCondition('YEAR(t.date_input) = :year');
				$params[':month'] = $month;
				$params[':year'] = $year;
			}
		}


		$params[':language_id'] = $languageId;
		$criteria->order = "t.date_input DESC";
		$criteria->params = $params;

		if ($limit !== false) {
			$criteria->limit = $limit;
		}

		$model = Blog::model()->findAll($criteria);

		return $model;
	}

	public function getMenu($languageId=1)
	{
		$criteria=new CDbCriteria;

		$criteria->select = "YEAR(t.date_input) as `year`, MONTH(t.date_input) as `month`, t.date_input";
		$criteria->join = "LEFT JOIN pg_blog_description ON pg_blog_description.blog_id=t.id";

		$params = array();

		$criteria->addCondition('pg_blog_description.language_id = :language_id');
		$params[':language_id'] = $languageId;
		$criteria->order = "date_input DESC";
		$criteria->params = $params;

		$model = Blog::model()->findAll($criteria);

		$data = array();
		foreach ($model as $key => $value) {
			$data[$value->year][$value->month] = $value->date_input;
		}

		$listMenu = array();
		foreach ($data as $key => $value) {
			foreach ($value as $k => $v) {
				$query2 = Yii::app()->db->createCommand("
					SELECT `t`.`id`, `d`.`title`, `d`.`content`, `t`.`date_input` FROM `blog` `t` INNER JOIN `pg_blog_description` `d`
					ON `t`.`id` = `d`.`blog_id`
					WHERE
					`t`.`active` = '1' AND
					`d`.`language_id` = $languageId AND
					YEAR(`date_input`) = '".$key."' AND
					MONTH(`date_input`) = '".$k."'
					ORDER BY `date_input` DESC
					")->query();

					$data2 = array();
					foreach ($query2 as $kul => $v) {
						$data2[] = array(
							'label'=>$v['title'],
							'url'=>array('/blog/detail', 'id'=> $v['id'], 'slug'=> Slug::create($v['title']) ), 
							// 'active'=>false,
						);
					}

				$listMenu[] = array(
					'label'=>'<i class="glyphicon glyphicon-plus"></i> &nbsp;'. Yii::app()->locale->getMonthName($k).' '.$key,
					'month'=>$k,
					'year'=>$key,
					'items'=>$data2,
				);

			}
		}

		return $listMenu;
	}

	public function getWriter($languageId=1)
	{
		$criteria=new CDbCriteria;

		$criteria->select = "t.*, pg_blog_description.title";
		$criteria->join = "
		LEFT JOIN pg_blog_description ON pg_blog_description.blog_id=t.id
		";

		$params = array();

		$criteria->addCondition('pg_blog_description.language_id = :language_id');
		$params[':language_id'] = $languageId;

admin/protected/controllers/BlogController.php
<?php

class BlogController extends Controller
{

	// public function actionD_index()
	// {
	// 	$this->pageTitle = 'Berita & Artikel - '.$this->pageTitle;
	// 	$this->layout='//layouts/column1';

	// 	$this->render('//blog/d_index', array(	
	// 	));
	// }

	// public function actionD_detail()
	// {
	// 	$this->pageTitle = 'Title News' . ' - News & Articles - '.$this->pageTitle;
	// 	$this->layout='//layouts/column1';

	// 	$this->render('//blog/d_detail', array(	
	// 	));
	// }

	public function actionIndex()
	{

		$criteria = new CDbCriteria;
		$criteria->with = array('description');
		$criteria->addCondition('active = "1"');
		$criteria->addCondition('description.language_id = :language_id');
		$criteria->params[':language_id'] = $this->languageID;
		$criteria->order = 'date_input DESC';

		$dataFeatured = new CActiveDataProvider('Blog', array(
			'criteria'=>$criteria,
		    'pagination'=>array(
		        'pageSize'=>2,
		    ),
		));
		$arrayFeatured = array();
		foreach ($dataFeatured->getData() as $key => $value) {
			$arrayFeatured[] = $value->id;
		}
		$criteria->addNotInCondition('t.id', $arrayFeatured);
		$dataBlog = new CActiveDataProvider('Blog', array(
			'criteria'=>$criteria,
		    'pagination'=>array(
		        'pageSize'=>6,
		    ),
		));

		$this->layout='//layouts/column2';
		$this->pageTitle = 'News & Articles - '.$this->pageTitle;
		$this->render('index', array(
			'dataBlog'=>$dataBlog,
			'dataFeatured'=>$dataFeatured,
		));
	}
	public function actionDetail($id)
	{
		$criteria = new CDbCriteria;
		$criteria->with = array('description');
		$criteria->addCondition('active = "1"');
		$criteria->addCondition('description.language_id = :language_id');
		$criteria->params[':language_id'] = $this->languageID;
		$criteria->addCondition('t.id = :id');
		$criteria->params[':id'] = $id;
		$criteria->order = 'date_input DESC';
		$dataBlog = Blog::model()->find($criteria);
		if($dataBlog===null)
			throw new CHttpException(404,'The requested page does not exist.');

		$criteria = new CDbCriteria;
		$criteria->order = 'RAND()';
		$criteria->addCondition('id != :id');
		$criteria->params[':id'] = $dataBlog->id;
		$dataBlogs = new CActiveDataProvider('Blog', array(
			'criteria'=>$criteria,
		    'pagination'=>array(
		        'pageSize'=>10,
		    ),
		));

		$this->pageTitle = $dataBlog->description->title . ' - News & Articles - '.$this->pageTitle;
		$this->layout='//layouts/column2';
		$this->render('detail', array(
			'dataBlog' => $dataBlog,
			'dataBlogs' => $dataBlogs,
			// 'menu'=>$menu,
			// 'data'=> $konten,
			// 'subMenu'=>$subMenu,
			// 'categoryData'=>$categoryData,
			// 'terbaru'=>$terbaru,
			// 'categoryName'=>$categoryName,
		));
	}

	public function actionList()
	{

		$this->layout='//layouts/home';

		// convert to list item menu
		$categoryName = Product::model()->getCategoryName();

		$konten = Blog::model()->getAllData(10, false, $this->languageID);

		$this->pageTitle = $konten['pageTitle'].' - ' . $this->pageTitle;
		if ($_GET['topik'] == 'topik-panduan-pemula') {
		$this->render('panduan', array(
			'categoryName'=>$categoryName,
			'data'=> $konten,
		));
		}elseif($_GET['topik'] == 'topik-workout-list'){
		$this->render('workout', array(
			'categoryName'=>$categoryName,
			'data'=> $konten,
		));
		}else{
		$this->render('list', array(
			'categoryName'=>$categoryName,
			'data'=> $konten,
		));
		}
	}
	public function actionCalculator()
	{

		$this->layout='//layouts/home';
		$this->pageTitle = 'Fitness Calculator | ' . $this->pageTitle;
		$this->render('calculator', array(
		));
	}
	public function actionCalc($type)
	{
		switch ($type) {
			case 'bmi':
				$tampilan = 'calc-bmi';
				break;
			
			case 'bmr':
				$tampilan = 'calc-bmr';
				break;
			
			case 'kalori':
				$tampilan = 'calc-kalori';
				break;
			
			case 'minum':
				$tampilan = 'calc-minum';
				break;
			
			case 'nutrisi':
				$tampilan = 'calc-nutrisi';
				break;
			
			default:
				$tampilan = 'calc-bmi';
				break;
		}

		$this->layout='//layoutsAdmin/mainKosong';
		$this->pageTitle = 'Fitness Calculator | ' . $this->pageTitle;
		$this->render($tampilan, array(
		));
	}

	// public function actionPanduan()
	// {

	// 	$this->layout='//layouts/home';
	// 	$this->pageTitle = 'Panduan Fitness untuk Pemula | ' . $this->pageTitle;
	// 	$this->render('panduan', array(
	// 	));
	// }
	// public function actionWorkout()
	// {

	// 	$this->layout='//layouts/home';
	// 	$this->pageTitle = 'Workout List Fitness | ' . $this->pageTitle;
	// 	$this->render('workout', array(
	// 	));
	// }
}

admin/protected/views/blog/calculator.php
<?php
$this->breadcrumbs = array(
    'Tips & Artikel'=>array('/blog/index'),
    'Fitness Calculator',
);
?>
<section class="promosi-banner2">
    <div class="prelatif container">

<div class="height-30"></div>
<div class="breadcrump-container margin-left-50">
    <div class="pull-left">
    <?php if(isset($this->breadcrumbs)):?>
        <?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
            'links'=>$this->breadcrumbs,
            'separator'=>'',
            'homeLink'=>CHtml::link('<i class="icon-home-breadcrumb"></i>',array('/home/index')),
        )); ?><!-- breadcrumbs -->
    <?php endif?>
    </div>
    <div class="pull-right">
        <div class="link-back margin-top-10"><a href="<?php echo CHtml::normalizeUrl(array('/blog/index')); ?>"><i class="glyphicon glyphicon-chevron-left"></i> Back</a></div>
    </div>
</div>
<div class="clear"></div>
<div class="height-5"></div>
<div class="prelatif">
<div class="product-list-warp back-white-product content-text product-landing-outer margin-left-50">
    <div class="padding-15 prelatif">
        <!-- inside goal content -->
        <div class="clear height-5"></div>
        <div class="height-3"></div>
        <div class="left back-title-landingproduct">
            <div class="text">
                Fitness Calculator
            </div>
        </div>
        <div class="left back-tail-title-landingproduct"></div>
        
        <!-- middle data -->
        <div class="clear height-50"></div>
        <div class="height-30"></div>
        <div class="row box-landingdata">
            <div class="col-md-4">
                <div class="out-back-pic">
                    <div class="back-pic">
                        <img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(290,305, '/asset/images/ill-calc.jpg' , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="">
                    </div>
                    <div class="back-pic-landingproduct">
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="desc left content-text">
                    <p>GaleriFitness.com telah mengambil waktu untuk membuat hidup setiap dari anda jauh lebih mudah, lagi. Kalkulator ini akan membuat lebih mudah bagi setiap orang untuk melakukan apa saja di internet termasuk untuk membuat program diet racikan anda sendiri!</p>


                </div>
            </div>
        </div>
        <div class="clear height-20"></div>

        <div class="box-outer-list-landing">
            <div class="title">Kalkulator Nutrisi Anda</div>
            <div class="clear height-35"></div>

            <div class="list-data-landingproduk">
                    
                <div class="item">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="pict">
                                <a href="<?php echo CHtml::normalizeUrl(array('/product/index', 'goal'=>$value->slug)); ?>">
                                <img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(290,183, '/asset/images/ill-calc-1.jpg' , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="description">
                                <span class="judul">Hitung Body Mass Index Anda !</span>
                                <div class="clear height-10"></div>
                                <div class="lines-red"></div>
                                <div class="clear height-15"></div>
                                <p>Body Mass Index (BMI) adalah calculator yang kami sediakan secara sederhana untuk mengukur apakah anda berada pada level kelebihan berat badan atau sebaliknya</p>
                                <a class="fancy-popup fancybox.ajax btn btn-add-to-cart bt-purple-product bt-view-produk" href="<?php echo CHtml::normalizeUrl(array('/blog/calc', 'type'=>'bmi')); ?>" >Hitung BMI</a>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="clear height-40"></div>
                    <div class="border-dashed"></div>
                    <div class="clear height-40"></div>
                
                <div class="item">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="pict">
                                <a href="<?php echo CHtml::normalizeUrl(array('/product/index', 'goal'=>$value->slug)); ?>">
                                <img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(290,183, '/asset/images/ill-calc-2.jpg' , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="description">
                                <span class="judul">Hitung Basal Metabolic Rate Anda !</span>
                                <div class="clear height-10"></div>
                                <div class="lines-red"></div>
                                <div class="clear height-15"></div>
                                <p>Basal Metabolic Rate (BMR) adalah jumlah energi yang dikeluarkan saat beristirahat di lingkungan yang netral dan pada iklim standar. Hitung BMR Anda dengan kalkulator yang berguna ini!</p>
                                <a class="fancy-popup fancybox.ajax btn btn-add-to-cart bt-purple-product bt-view-produk" href="<?php echo CHtml::normalizeUrl(array('/blog/calc', 'type'=>'bmr')); ?>" >Hitung BMR</a>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="clear height-40"></div>
                    <div class="border-dashed"></div>
                    <div class="clear height-40"></div>
                
                <div class="item">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="pict">
                                <a href="<?php echo CHtml::normalizeUrl(array('/product/index', 'goal'=>$value->slug)); ?>">
                                <img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(290,183, '/asset/images/ill-calc-3.jpg' , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="description">
                                <span class="judul">Kalkulasi kebutuhan kalori Anda setiap hari !</span>
                                <div class="clear height-10"></div>
                                <div class="lines-red"></div>
                                <div class="clear height-15"></div>
                                <p>Menghitung BMR saja tentunya tidak cukup ! Karena anda pada dasarnya tidak akan berdiam diri saja di kamar tidur tanpa melakukan aktivitas apapun. Hitung kebutuhan kalori anda apabila anda ingin mempertahankan berat badan anda berdasar aktivitas yang anda lakukan sehari-hari !</p>
                                <a class="fancy-popup fancybox.ajax btn btn-add-to-cart bt-purple-product bt-view-produk" href="<?php echo CHtml::normalizeUrl(array('/blog/calc', 'type'=>'kalori')); ?>" >Kalkulasi</a>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="clear height-40"></div>
                    <div class="border-dashed"></div>
                    <div class="clear height-40"></div>
                
                <div class="item">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="pict">
                                <a href="<?php echo CHtml::normalizeUrl(array('/product/index', 'goal'=>$value->slug)); ?>">
                                <img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(290,183, '/asset/images/ill-calc-4.jpg' , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="description">
                                <span class="judul">Kalkulasi Kebutuhan Minum Air Putih Anda Setiap Hari !</span>
                                <div class="clear height-10"></div>
                                <div class="lines-red"></div>
                                <div class="clear height-15"></div>
                                <p>Air sangat penting bagi kesehatan kita. Air memiliki banyak manfaat kesehatan dan berpengaruh langsung pada latihan anda. Cari tahu berapa banyak air yang harus Anda minum dengan kalkulator berguna di bawah ini!</p>
                                <a class="fancy-popup fancybox.ajax btn btn-add-to-cart bt-purple-product bt-view-produk" href="<?php echo CHtml::normalizeUrl(array('/blog/calc', 'type'=>'minum')); ?>" >Kalkulasi</a>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="clear height-40"></div>
                    <div class="border-dashed"></div>
                    <div class="clear height-40"></div>
                
                <div class="item">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="pict">
                                <a href="<?php echo CHtml::normalizeUrl(array('/product/index', 'goal'=>$value->slug)); ?>">
                                <img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(290,183, '/asset/images/ill-calc-5.jpg' , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="description">
                                <span class="judul">Kalkulasi Kebutuhan Asupan Nutrisi Untuk Tujuan Fitness Anda !</span>
                                <div class="clear height-10"></div>
                                <div class="lines-red"></div>
                                <div class="clear height-15"></div>
                                <p>Dengan kalkulator ini anda dapat menghitung seberapa besar kalori beserta dengan makronutrisinya (protein, karbohidrat dan lemak) sesuai dengan tujuan anda (menaikkan atau menurunkan berat badan anda) </p>
                                <a class="fancy-popup fancybox.ajax btn btn-add-to-cart bt-purple-product bt-view-produk" href="<?php echo CHtml::normalizeUrl(array('/blog/calc', 'type'=>'nutrisi')); ?>" >Kalkulasi</a>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="clear height-40"></div>
                    <div class="border-dashed"></div>
                    <div class="clear height-40"></div>
                
                <div class="clear"></div>
            </div>

            <div class="clear"></div>
        </div>
        <div class="clear height-50"></div>
        <!-- middle data -->

        <!-- inside goal content -->
        <div class="clear"></div>
    </div>
</div>
<div class="back-shadow-blockwhite-product"></div>
</div>
<div class="clear height-30"></div>
    <div class="pull-right">
        <div class="text-bottom-product text-left">
            <p>
            <b>Galerifitness.com - Suplemen Fitness - WHEY PROTEIN</b> <br>
            Galerifitness menjual suplemen fitness atau produk FAT LOSS merk asli resmi / original dengan harga terbaik. Pembeli produk Galerifitness.com FAT LOSS di Surabaya, Jakarta, Bali serta seluruh Indonesia akan memperoleh keuntungan berbelanja dengan harga terbaik dan lebih murah.
            </p>
        </div>
    </div>
<div class="clear height-20"></div>

</section>

admin/protected/views/blog/detail.php
<section class="outers_page_static back_cream mh500 back_grey_pattern">
  <div class="insides sub_page_static about_us">
    <div class="prelatife container">
      <div class="clear height-50"></div><div class="height-10"></div>

      <div class="content-text insides_static">
        <h1 class="title_page">BLOGS</h1>
        <div class="clear"></div>
        <h3 class="tagline"><?php echo $dataBlog->description->title ?></h3>
        <div class="clear"></div>
        <div class="row details_cont_articles">
          <div class="col-md-9 text-left">
            <div class="left_cont">
              <div class="mw906">

                <img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(980,1000, '/images/blog/'.$dataBlog->image , array('method' => 'resize', 'quality' => '90')) ?>" alt="">

                <?php echo $dataBlog->description->content ?>

                <div class="clear height-10"></div>
                <div class="shares-text text-left p_shares_article">
                    <span class="inline-t">SHARE</span>&nbsp; / &nbsp;<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=#">FACEBOOK</a>&nbsp; /
                    &nbsp;<a target="_blank" href="https://plus.google.com/share?url=#">GOOGLE PLUS</a>&nbsp; /
                    &nbsp;<a target="_blank" href="https://twitter.com/home?status=#">TWITTER</a>
                </div>

                <div class="clear"></div>
              </div>
            </div>

          </div>
          <div class="col-md-3 text-left">
            <div class="right_cont">
              <div class="padding-left-25">
                  <span class="sub_page_title">Other Blogs</span>
              </div>
              <div class="clear"></div>
              <div class="right_sub_menu">
                <ul class="list-unstyled">
                    <?php foreach ($dataBlogs->getData() as $key => $value): ?>
                        
                  <li><a href="<?php echo CHtml::normalizeUrl(array('detail', 'id'=>$value->id)); ?>"><?php echo $value->description->title ?></a></li>
                    <?php endforeach ?>
                </ul>
                <div class="clear"></div>
              </div>

              <div class="clear"></div>
            </div>
            <div class="clear"></div>
          </div>
        </div>
        

        <div class="clear"></div>
      </div>
      
      <div class="clear height-20"></div>
      <div class="clear height-50"></div>
    </div>
    <div class="clear"></div>
  </div>
</section>